name: build-push-docker

# Controls when the workflow will run
on:
  # Triggers the workflow on push events for the master branch
  push:
    branches: [ master ]
    paths:
      - 'Dockerfile'
      - '**.sh'
      - '**.txt'
  pull_request:
    branches: [ master ]
    paths:
      - 'Dockerfile'
      - '**.sh'
      - '**.txt'
  # Allows this workflow to be ran manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checkout repository 
      - uses: actions/checkout@v3

      - name: Set Timezone
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "America/Chicago"

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Generate Version Number
        run: |
          eval "$(date +'today=%F now=%s')"
          IMG_VER="$(date +%Y.%m.%d).$((now - $(date -d "$today 0" +%s)))"
          echo "IMG_VER=${IMG_VER}" >> $GITHUB_ENV
          BUILD_DATE=$(date +%Y.%m.%d)
          echo "BUILD_DATE=${BUILD_DATE}" >> $GITHUB_ENV
          
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.5.0
        
      - name: Build and push Docker images
        uses: docker/build-push-action@v4.0.0
        with:
          build-args: BUILD_DATE=${{ env.BUILD_DATE }}
          context: .
          pull: true
          push: ${{ github.event_name != 'pull_request' }}
          tags: cubeworx/mcbe-server:${{ env.IMG_VER }},cubeworx/mcbe-server:latest

      - uses: ethomson/send-tweet-action@v1.0.0
        if: github.event_name != 'pull_request'
        with:
          status: "New version of CubeWorx Minecraft Bedrock Edition Server Image released: https://hub.docker.com/r/cubeworx/mcbe-server/tags?page=1&ordering=last_updated&name=${{ env.IMG_VER }}"
          consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
