name: Build & Push Docker Image

# Controls when the workflow will run
on:
  # Triggers the workflow on push events for the master branch
  push:
    branches: [ master ]
  # Allows this workflow to be ran manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checkout repository 
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          env | sort
          ls -alh
